# Generated by Django 3.1.7 on 2022-09-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
